Rewrite, reformat, improve

diff --git a/kubectl-socks5-proxy b/kubectl-socks5-proxy
--- a/kubectl-socks5-proxy
+++ b/kubectl-socks5-proxy
@@ -3,13 +3,13 @@
 # A kubectl plugin that creates a local SOCKS5 proxy through which you can access to pods/services in a Kubernetes cluster
 #
 
-[[ -n $DEBUG ]] && set -x -e
+[[ -n "$DEBUG" ]] && set -x -e
 
-MAX_POD_CREATION_TIME=10  # unit: second
-DEFAULT_NAME=$(echo ${USER}-proxy|sed -e 's/[^[:alnum:]|-]//g'|tr '[:upper:]' '[:lower:]')
+# shellcheck disable=2001
+DEFAULT_PODNAME=$(sed -e 's/[^[:alnum:]|-]//g' <<< "socks5-proxy-${USER:-$(date '+%s')}" | tr '[:upper:]' '[:lower:]')
 DEFAULT_PORT=1080
-DEFAULT_PROXY_NAMESPACE=default
-DEFAULT_PROXY_IMAGE=serjs/go-socks5-proxy
+DEFAULT_PODNAMESPACE=default
+DEFAULT_IMAGE=serjs/go-socks5-proxy
 
 help(){
   echo "Usage: "
@@ -21,49 +21,57 @@ help(){
 options(){
   cat << EOF
 Options:
+  -c, --context <namespace>     Kubernetes context to create SOCKS5 proxy server in
+                                Default: Current context
+
   -n, --namespace <namespace>   Namespace to create SOCKS5 proxy server in
-                                Default: ${DEFAULT_PROXY_NAMESPACE}
+                                Default: ${DEFAULT_PODNAMESPACE}
 
   -p, --port <local port>       Local port to be forwarded to the SOCKS5 proxy server (Pod)
-                                A client connects to this port, then the connection is forwarded to the 
+                                A client connects to this port, then the connection is forwarded to the
                                 SOCKS5 proxy server, which is then forwareded to the destination server
                                 Default: ${DEFAULT_PORT}
 
   -N, --name <pod name>         Name to give the pod in the cluster
-                                Default: ${DEFAULT_NAME}
+                                Default: ${DEFAULT_PODNAME}
 
-  -i, --image <socks5 image>    Set the image used as socks5 proxy server
-                                Default: ${DEFAULT_PROXY_IMAGE}
+  -i, --image <socks5 image>    Set the image used as SOCKS5 proxy server
+                                Default: ${DEFAULT_IMAGE}
 
-  --skip-cleanup-proxy          Skip cearning up SOCKS5 proxy pod
-                                Default: Cleaning up SOCKS5 proxy pod at the end
+  --skip-cleanup                Skip cleanup of the SOCKS5 proxy pod
+                                Default: Delete SOCKS5 proxy pod at the end
 
   -h, --help                    Show this message
 EOF
 }
 
 cleanup_proxy(){
-  local namespace="$1"
+  local context="$1" namespace="$2" podname="$3"
   echo "Clearning up SOCKS5 proxy server (Pod)..."
-  kubectl delete pod ${podname} -n ${namespace}
+  kubectl --context "$context" delete pod "${podname}" --namespace "${namespace}"
 }
 
 run_proxy(){
-  local namespace="$1"
-  local port="$2"
-  local image="$3"
+  local context="$1"
+  local namespace="$2"
+  local port="$3"
+  local image="$4"
+  local r
 
   # Install an SOCKS5 proxy server if not yet installed
-  r=$(kubectl get pod ${podname} -n ${namespace} 2>/dev/null | tail -1 | awk '{print $1}') # 
-  if [ "${r}" != "${podname}" ];then
+  r=$(kubectl --context "${context}" get pod "${podname}" --namespace "${namespace}" 2>/dev/null | tail -1 | awk '{print $1}')
+
+  if [[ "${r}" != "${podname}" ]]
+  then
     echo "Creating SOCKS5 Proxy (Pod)..."
-    cat <<EOF | kubectl apply -n ${namespace} -f -
+    cat <<EOF | kubectl --context "${context}" apply --namespace "${namespace}" -f -
 apiVersion: v1
 kind: Pod
 metadata:
   name: ${podname}
   labels:
     env: test
+    owner: ${USER}
 spec:
   containers:
   - name: ${podname}
@@ -74,96 +82,90 @@ spec:
     "kubernetes.io/os": linux
 EOF
 
-    # Wait until SOCKS5 proxy server gets ready
-    c=1
-    while [[ ${c} -le ${MAX_POD_CREATION_TIME} ]];
-    do
-      pod_status=$(kubectl get pod ${podname} -n ${namespace} 2>/dev/null | tail -1 | awk '{print $3}')
-      if [ "${pod_status}" = "Running" ]; then
-        break
-      fi
-      (( c++ ))
-      sleep 1
-    done
   fi
+
+  kubectl --context "$context" --namespace "$namespace" \
+    wait --for=condition=Ready --timeout=60s "$podname" >/dev/null
 
   echo "Starting a local SOCKS5 Proxy (localhost:${port})..."
   echo ""
   echo "The proxy Pod can be cleaned up with ^C (if not in background),"
-  echo "or with a command \"kubectl delete pod ${podname} -n ${namespace}\""
+  echo "or with a command \"kubectl --context \"${context}\" delete pod  -n \"${namespace}\" \"${podname}\"\""
   echo ""
+
   # Setup portforward
-  kubectl port-forward -n ${namespace} ${podname} $port:1080 
+  kubectl --context "${context}" --namespace "${namespace}" port-forward "${podname}" "${port}:1080"
 }
 
 plugin_main() {
-  skip_cleanup_proxy=no
-  while [ $# -gt 0 ] ; do
-    nSkip=1
+  local skip_pod_deletion
+  local namespace port image podname context
+
+  while [[ $# -gt 0 ]]
+  do
     case $1 in
-      "-h" | "--help")
+      -h|--help)
         help
         exit 0
-      ;;
-      "--skip-cleanup-proxy")
-        skip_cleanup_proxy=yes
-      ;;
-      "-n" | "--namespace" )
-        namespace=$2
-        nSkip=2
-      ;;
-      "-p" | "--port" )
-        port=$2
-        nSkip=2
-      ;;
-      "-N" | "--name" )
-        podname=$2
-        nSkip=2
-      ;;
-      "-i" | "--image" )
-        image=$2
-        nSkip=2
-      ;;
+        ;;
+      --skip-cleanup-proxy)
+        skip_pod_deletion=1
+        shift
+        ;;
+      -c|--ctx|--context)
+        context="$2"
+        shift 2
+        ;;
+      -n|--namespace)
+        namespace="$2"
+        shift 2
+        ;;
+      -p|--port)
+        port="$2"
+        shift 2
+        ;;
+      -N|--name)
+        podname="$2"
+        shift 2
+        ;;
+      -i|--image)
+        image="$2"
+        shift 2
+        ;;
       *)
         help >&2
-        exit 1
+        exit 2
       ;;
     esac
-    shift $nSkip
   done
 
-  if [[ "$(type kubectl &>/dev/null; echo $?)" -eq 1 ]]; then
-    echo "Error: missing kubectl command" >&2
-    echo "Please install kubectl (https://kubernetes.io/docs/tasks/tools/install-kubectl/)" >&2
+  if ! command -v kubectl &>/dev/null
+  then
+    {
+      echo "Error: missing kubectl command"
+      echo "Please install kubectl (https://kubernetes.io/docs/tasks/tools/install-kubectl/)"
+    } >&2
     exit 1
   fi
 
-  if [ ! -n "${namespace}" ]; then
-    namespace=${DEFAULT_PROXY_NAMESPACE}
-  fi
-  echo "using: namespace=${namespace}"
+  context=${context:-$(kubectl config current-context)}
+  namespace=${namespace:-${DEFAULT_PODNAMESPACE}}
+  port=${port:-${DEFAULT_PORT}}
+  image=${image:-${DEFAULT_IMAGE}}
+  podname=${podname:-${DEFAULT_PODNAME}}
 
-  if [ ! -n "${port}" ]; then
-    port=${DEFAULT_PORT}
-  fi
-  echo "using: port=${port}"
+  echo "using: context=\"${context}\" namespace=\"${namespace}\" port=\"${port}\" name=\"${podname}\" image=\"${image}\""
 
-  if [ ! -n "${podname}" ]; then
-    podname=${DEFAULT_NAME}
-  fi
-  echo "using: name=${podname}"
-
-  if [ ! -n "${image}" ]; then
-    image=${DEFAULT_PROXY_IMAGE}
-  fi
-  echo "using: image=${image}"
-
-  run_proxy "${namespace}" "${port}" "${image}"
+  run_proxy "${context}" "${namespace}" "${port}" "${image}"
 
   # Cleaning up SOCKS5 proxy server if needed
-  if [ "${skip_cleanup_proxy}" = "no" ]; then
-    cleanup_proxy "${namespace}"
+  if [[ -z "${skip_pod_deletion}" ]]
+  then
+    cleanup_proxy "${context}" "${namespace}" "${podname}"
   fi
 }
 
-plugin_main "$@"
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]
+then
+  plugin_main "$@"
+fi
